
function Initialize-Named-Location {
    param(
        [Parameter(Mandatory=$true)]
        [string[]]$CountryCodes,
        
        [Parameter(Mandatory=$false)]
        [string]$DisplayName = "Vacation Mode Location",
        
        [Parameter(Mandatory=$false)]
        [bool]$IncludeUnknownCountriesAndRegions = $false
    )

    # Array for Country names.
    @(
    [PSCustomObject]@{Name = "Afghanistan"; Code = "AF"},
    [PSCustomObject]@{Name = "Albania"; Code = "AL"},
    [PSCustomObject]@{Name = "Algeria"; Code = "DZ"},
    [PSCustomObject]@{Name = "American Samoa"; Code = "AS"},
    [PSCustomObject]@{Name = "Andorra"; Code = "AD"},
    [PSCustomObject]@{Name = "Angola"; Code = "AO"},
    [PSCustomObject]@{Name = "Anguilla"; Code = "AI"},
    [PSCustomObject]@{Name = "Antarctica"; Code = "AQ"},
    [PSCustomObject]@{Name = "Antigua and Barbuda"; Code = "AG"},
    [PSCustomObject]@{Name = "Argentina"; Code = "AR"},
    [PSCustomObject]@{Name = "Armenia"; Code = "AM"},
    [PSCustomObject]@{Name = "Aruba"; Code = "AW"},
    [PSCustomObject]@{Name = "Australia"; Code = "AU"},
    [PSCustomObject]@{Name = "Austria"; Code = "AT"},
    [PSCustomObject]@{Name = "Azerbaijan"; Code = "AZ"},
    [PSCustomObject]@{Name = "Bahamas"; Code = "BS"},
    [PSCustomObject]@{Name = "Bahrain"; Code = "BH"},
    [PSCustomObject]@{Name = "Bangladesh"; Code = "BD"},
    [PSCustomObject]@{Name = "Barbados"; Code = "BB"},
    [PSCustomObject]@{Name = "Belarus"; Code = "BY"},
    [PSCustomObject]@{Name = "Belgium"; Code = "BE"},
    [PSCustomObject]@{Name = "Belize"; Code = "BZ"},
    [PSCustomObject]@{Name = "Benin"; Code = "BJ"},
    [PSCustomObject]@{Name = "Bermuda"; Code = "BM"},
    [PSCustomObject]@{Name = "Bhutan"; Code = "BT"},
    [PSCustomObject]@{Name = "Bolivia"; Code = "BO"},
    [PSCustomObject]@{Name = "Bonaire"; Code = "BQ"},
    [PSCustomObject]@{Name = "Bosnia and Herzegovina"; Code = "BA"},
    [PSCustomObject]@{Name = "Botswana"; Code = "BW"},
    [PSCustomObject]@{Name = "Bouvet Island"; Code = "BV"},
    [PSCustomObject]@{Name = "Brazil"; Code = "BR"},
    [PSCustomObject]@{Name = "British Indian Ocean Territory"; Code = "IO"},
    [PSCustomObject]@{Name = "Brunei"; Code = "BN"},
    [PSCustomObject]@{Name = "Bulgaria"; Code = "BG"},
    [PSCustomObject]@{Name = "Burkina Faso"; Code = "BF"},
    [PSCustomObject]@{Name = "Burundi"; Code = "BI"},
    [PSCustomObject]@{Name = "Cabo Verde"; Code = "CV"},
    [PSCustomObject]@{Name = "Cambodia"; Code = "KH"},
    [PSCustomObject]@{Name = "Cameroon"; Code = "CM"},
    [PSCustomObject]@{Name = "Canada"; Code = "CA"},
    [PSCustomObject]@{Name = "Cayman Islands"; Code = "KY"},
    [PSCustomObject]@{Name = "Central African Republic"; Code = "CF"},
    [PSCustomObject]@{Name = "Chad"; Code = "TD"},
    [PSCustomObject]@{Name = "Chile"; Code = "CL"},
    [PSCustomObject]@{Name = "China"; Code = "CN"},
    [PSCustomObject]@{Name = "Christmas Island"; Code = "CX"},
    [PSCustomObject]@{Name = "Cocos (Keeling) Islands"; Code = "CC"},
    [PSCustomObject]@{Name = "Colombia"; Code = "CO"},
    [PSCustomObject]@{Name = "Comoros"; Code = "KM"},
    [PSCustomObject]@{Name = "Congo"; Code = "CG"},
    [PSCustomObject]@{Name = "Congo (DRC)"; Code = "CD"},
    [PSCustomObject]@{Name = "Cook Islands"; Code = "CK"},
    [PSCustomObject]@{Name = "Costa Rica"; Code = "CR"},
    [PSCustomObject]@{Name = "Côte d'Ivoire"; Code = "CI"},
    [PSCustomObject]@{Name = "Croatia"; Code = "HR"},
    [PSCustomObject]@{Name = "Cuba"; Code = "CU"},
    [PSCustomObject]@{Name = "Curaçao"; Code = "CW"},
    [PSCustomObject]@{Name = "Cyprus"; Code = "CY"},
    [PSCustomObject]@{Name = "Czech Republic"; Code = "CZ"},
    [PSCustomObject]@{Name = "Denmark"; Code = "DK"},
    [PSCustomObject]@{Name = "Djibouti"; Code = "DJ"},
    [PSCustomObject]@{Name = "Dominica"; Code = "DM"},
    [PSCustomObject]@{Name = "Dominican Republic"; Code = "DO"},
    [PSCustomObject]@{Name = "Ecuador"; Code = "EC"},
    [PSCustomObject]@{Name = "Egypt"; Code = "EG"},
    [PSCustomObject]@{Name = "El Salvador"; Code = "SV"},
    [PSCustomObject]@{Name = "Equatorial Guinea"; Code = "GQ"},
    [PSCustomObject]@{Name = "Eritrea"; Code = "ER"},
    [PSCustomObject]@{Name = "Estonia"; Code = "EE"},
    [PSCustomObject]@{Name = "Eswatini"; Code = "SZ"},
    [PSCustomObject]@{Name = "Ethiopia"; Code = "ET"},
    [PSCustomObject]@{Name = "Falkland Islands"; Code = "FK"},
    [PSCustomObject]@{Name = "Faroe Islands"; Code = "FO"},
    [PSCustomObject]@{Name = "Fiji"; Code = "FJ"},
    [PSCustomObject]@{Name = "Finland"; Code = "FI"},
    [PSCustomObject]@{Name = "France"; Code = "FR"},
    [PSCustomObject]@{Name = "French Guiana"; Code = "GF"},
    [PSCustomObject]@{Name = "French Polynesia"; Code = "PF"},
    [PSCustomObject]@{Name = "French Southern Territories"; Code = "TF"},
    [PSCustomObject]@{Name = "Gabon"; Code = "GA"},
    [PSCustomObject]@{Name = "Gambia"; Code = "GM"},
    [PSCustomObject]@{Name = "Georgia"; Code = "GE"},
    [PSCustomObject]@{Name = "Germany"; Code = "DE"},
    [PSCustomObject]@{Name = "Ghana"; Code = "GH"},
    [PSCustomObject]@{Name = "Gibraltar"; Code = "GI"},
    [PSCustomObject]@{Name = "Greece"; Code = "GR"},
    [PSCustomObject]@{Name = "Greenland"; Code = "GL"},
    [PSCustomObject]@{Name = "Grenada"; Code = "GD"},
    [PSCustomObject]@{Name = "Guadeloupe"; Code = "GP"},
    [PSCustomObject]@{Name = "Guam"; Code = "GU"},
    [PSCustomObject]@{Name = "Guatemala"; Code = "GT"},
    [PSCustomObject]@{Name = "Guernsey"; Code = "GG"},
    [PSCustomObject]@{Name = "Guinea"; Code = "GN"},
    [PSCustomObject]@{Name = "Guinea-Bissau"; Code = "GW"},
    [PSCustomObject]@{Name = "Guyana"; Code = "GY"},
    [PSCustomObject]@{Name = "Haiti"; Code = "HT"},
    [PSCustomObject]@{Name = "Heard Island and McDonald Islands"; Code = "HM"},
    [PSCustomObject]@{Name = "Holy See"; Code = "VA"},
    [PSCustomObject]@{Name = "Honduras"; Code = "HN"},
    [PSCustomObject]@{Name = "Hong Kong SAR"; Code = "HK"},
    [PSCustomObject]@{Name = "Hungary"; Code = "HU"},
    [PSCustomObject]@{Name = "Iceland"; Code = "IS"},
    [PSCustomObject]@{Name = "India"; Code = "IN"},
    [PSCustomObject]@{Name = "Indonesia"; Code = "ID"},
    [PSCustomObject]@{Name = "Iran"; Code = "IR"},
    [PSCustomObject]@{Name = "Iraq"; Code = "IQ"},
    [PSCustomObject]@{Name = "Ireland"; Code = "IE"},
    [PSCustomObject]@{Name = "Isle of Man"; Code = "IM"},
    [PSCustomObject]@{Name = "Israel"; Code = "IL"},
    [PSCustomObject]@{Name = "Italy"; Code = "IT"},
    [PSCustomObject]@{Name = "Jamaica"; Code = "JM"},
    [PSCustomObject]@{Name = "Japan"; Code = "JP"},
    [PSCustomObject]@{Name = "Jersey"; Code = "JE"},
    [PSCustomObject]@{Name = "Jordan"; Code = "JO"},
    [PSCustomObject]@{Name = "Kazakhstan"; Code = "KZ"},
    [PSCustomObject]@{Name = "Kenya"; Code = "KE"},
    [PSCustomObject]@{Name = "Kiribati"; Code = "KI"},
    [PSCustomObject]@{Name = "Korea"; Code = "KR"},
    [PSCustomObject]@{Name = "Kosovo"; Code = "XK"},
    [PSCustomObject]@{Name = "Kuwait"; Code = "KW"},
    [PSCustomObject]@{Name = "Kyrgyzstan"; Code = "KG"},
    [PSCustomObject]@{Name = "Laos"; Code = "LA"},
    [PSCustomObject]@{Name = "Latvia"; Code = "LV"},
    [PSCustomObject]@{Name = "Lebanon"; Code = "LB"},
    [PSCustomObject]@{Name = "Lesotho"; Code = "LS"},
    [PSCustomObject]@{Name = "Liberia"; Code = "LR"},
    [PSCustomObject]@{Name = "Libya"; Code = "LY"},
    [PSCustomObject]@{Name = "Liechtenstein"; Code = "LI"},
    [PSCustomObject]@{Name = "Lithuania"; Code = "LT"},
    [PSCustomObject]@{Name = "Luxembourg"; Code = "LU"},
    [PSCustomObject]@{Name = "Macao SAR"; Code = "MO"},
    [PSCustomObject]@{Name = "Madagascar"; Code = "MG"},
    [PSCustomObject]@{Name = "Malawi"; Code = "MW"},
    [PSCustomObject]@{Name = "Malaysia"; Code = "MY"},
    [PSCustomObject]@{Name = "Maldives"; Code = "MV"},
    [PSCustomObject]@{Name = "Mali"; Code = "ML"},
    [PSCustomObject]@{Name = "Malta"; Code = "MT"},
    [PSCustomObject]@{Name = "Marshall Islands"; Code = "MH"},
    [PSCustomObject]@{Name = "Martinique"; Code = "MQ"},
    [PSCustomObject]@{Name = "Mauritania"; Code = "MR"},
    [PSCustomObject]@{Name = "Mauritius"; Code = "MU"},
    [PSCustomObject]@{Name = "Mayotte"; Code = "YT"},
    [PSCustomObject]@{Name = "Mexico"; Code = "MX"},
    [PSCustomObject]@{Name = "Micronesia"; Code = "FM"},
    [PSCustomObject]@{Name = "Moldova"; Code = "MD"},
    [PSCustomObject]@{Name = "Monaco"; Code = "MC"},
    [PSCustomObject]@{Name = "Mongolia"; Code = "MN"},
    [PSCustomObject]@{Name = "Montenegro"; Code = "ME"},
    [PSCustomObject]@{Name = "Montserrat"; Code = "MS"},
    [PSCustomObject]@{Name = "Morocco"; Code = "MA"},
    [PSCustomObject]@{Name = "Mozambique"; Code = "MZ"},
    [PSCustomObject]@{Name = "Myanmar"; Code = "MM"},
    [PSCustomObject]@{Name = "Namibia"; Code = "NA"},
    [PSCustomObject]@{Name = "Nauru"; Code = "NR"},
    [PSCustomObject]@{Name = "Nepal"; Code = "NP"},
    [PSCustomObject]@{Name = "Netherlands"; Code = "NL"},
    [PSCustomObject]@{Name = "New Caledonia"; Code = "NC"},
    [PSCustomObject]@{Name = "New Zealand"; Code = "NZ"},
    [PSCustomObject]@{Name = "Nicaragua"; Code = "NI"},
    [PSCustomObject]@{Name = "Niger"; Code = "NE"},
    [PSCustomObject]@{Name = "Nigeria"; Code = "NG"},
    [PSCustomObject]@{Name = "Niue"; Code = "NU"},
    [PSCustomObject]@{Name = "Norfolk Island"; Code = "NF"},
    [PSCustomObject]@{Name = "North Korea"; Code = "KP"},
    [PSCustomObject]@{Name = "North Macedonia"; Code = "MK"},
    [PSCustomObject]@{Name = "Northern Mariana Islands"; Code = "MP"},
    [PSCustomObject]@{Name = "Norway"; Code = "NO"},
    [PSCustomObject]@{Name = "Oman"; Code = "OM"},
    [PSCustomObject]@{Name = "Pakistan"; Code = "PK"},
    [PSCustomObject]@{Name = "Palau"; Code = "PW"},
    [PSCustomObject]@{Name = "Palestinian Authority"; Code = "PS"},
    [PSCustomObject]@{Name = "Panama"; Code = "PA"},
    [PSCustomObject]@{Name = "Papua New Guinea"; Code = "PG"},
    [PSCustomObject]@{Name = "Paraguay"; Code = "PY"},
    [PSCustomObject]@{Name = "Peru"; Code = "PE"},
    [PSCustomObject]@{Name = "Philippines"; Code = "PH"},
    [PSCustomObject]@{Name = "Pitcairn Islands"; Code = "PN"},
    [PSCustomObject]@{Name = "Poland"; Code = "PL"},
    [PSCustomObject]@{Name = "Portugal"; Code = "PT"},
    [PSCustomObject]@{Name = "Puerto Rico"; Code = "PR"},
    [PSCustomObject]@{Name = "Qatar"; Code = "QA"},
    [PSCustomObject]@{Name = "Réunion"; Code = "RE"},
    [PSCustomObject]@{Name = "Romania"; Code = "RO"},
    [PSCustomObject]@{Name = "Russia"; Code = "RU"},
    [PSCustomObject]@{Name = "Rwanda"; Code = "RW"},
    [PSCustomObject]@{Name = "Saint Barthélemy"; Code = "BL"},
    [PSCustomObject]@{Name = "Saint Kitts and Nevis"; Code = "KN"},
    [PSCustomObject]@{Name = "Saint Lucia"; Code = "LC"},
    [PSCustomObject]@{Name = "Saint Martin"; Code = "MF"},
    [PSCustomObject]@{Name = "Saint Pierre and Miquelon"; Code = "PM"},
    [PSCustomObject]@{Name = "Saint Vincent and the Grenadines"; Code = "VC"},
    [PSCustomObject]@{Name = "Samoa"; Code = "WS"},
    [PSCustomObject]@{Name = "San Marino"; Code = "SM"},
    [PSCustomObject]@{Name = "São Tomé and Príncipe"; Code = "ST"},
    [PSCustomObject]@{Name = "Saudi Arabia"; Code = "SA"},
    [PSCustomObject]@{Name = "Senegal"; Code = "SN"},
    [PSCustomObject]@{Name = "Serbia"; Code = "RS"},
    [PSCustomObject]@{Name = "Seychelles"; Code = "SC"},
    [PSCustomObject]@{Name = "Sierra Leone"; Code = "SL"},
    [PSCustomObject]@{Name = "Singapore"; Code = "SG"},
    [PSCustomObject]@{Name = "Sint Maarten"; Code = "SX"},
    [PSCustomObject]@{Name = "Slovakia"; Code = "SK"},
    [PSCustomObject]@{Name = "Slovenia"; Code = "SI"},
    [PSCustomObject]@{Name = "Solomon Islands"; Code = "SB"},
    [PSCustomObject]@{Name = "Somalia"; Code = "SO"},
    [PSCustomObject]@{Name = "South Africa"; Code = "ZA"},
    [PSCustomObject]@{Name = "South Georgia and South Sandwich Islands"; Code = "GS"},
    [PSCustomObject]@{Name = "South Sudan"; Code = "SS"},
    [PSCustomObject]@{Name = "Spain"; Code = "ES"},
    [PSCustomObject]@{Name = "Sri Lanka"; Code = "LK"},
    [PSCustomObject]@{Name = "St Helena, Ascension, Tristan da Cunha"; Code = "SH"},
    [PSCustomObject]@{Name = "Sudan"; Code = "SD"},
    [PSCustomObject]@{Name = "Suriname"; Code = "SR"},
    [PSCustomObject]@{Name = "Svalbard"; Code = "SJ"},
    [PSCustomObject]@{Name = "Sweden"; Code = "SE"},
    [PSCustomObject]@{Name = "Switzerland"; Code = "CH"},
    [PSCustomObject]@{Name = "Syria"; Code = "SY"},
    [PSCustomObject]@{Name = "Taiwan"; Code = "TW"},
    [PSCustomObject]@{Name = "Tajikistan"; Code = "TJ"},
    [PSCustomObject]@{Name = "Tanzania"; Code = "TZ"},
    [PSCustomObject]@{Name = "Thailand"; Code = "TH"},
    [PSCustomObject]@{Name = "Timor-Leste"; Code = "TL"},
    [PSCustomObject]@{Name = "Togo"; Code = "TG"},
    [PSCustomObject]@{Name = "Tokelau"; Code = "TK"},
    [PSCustomObject]@{Name = "Tonga"; Code = "TO"},
    [PSCustomObject]@{Name = "Trinidad and Tobago"; Code = "TT"},
    [PSCustomObject]@{Name = "Tunisia"; Code = "TN"},
    [PSCustomObject]@{Name = "Turkey"; Code = "TR"},
    [PSCustomObject]@{Name = "Turkmenistan"; Code = "TM"},
    [PSCustomObject]@{Name = "Turks and Caicos Islands"; Code = "TC"},
    [PSCustomObject]@{Name = "Tuvalu"; Code = "TV"},
    [PSCustomObject]@{Name = "U.S. Outlying Islands"; Code = "UM"},
    [PSCustomObject]@{Name = "U.S. Virgin Islands"; Code = "VI"},
    [PSCustomObject]@{Name = "Uganda"; Code = "UG"},
    [PSCustomObject]@{Name = "Ukraine"; Code = "UA"},
    [PSCustomObject]@{Name = "United Arab Emirates"; Code = "AE"},
    [PSCustomObject]@{Name = "United Kingdom"; Code = "GB"},
    [PSCustomObject]@{Name = "United States"; Code = "US"},
    [PSCustomObject]@{Name = "Uruguay"; Code = "UY"},
    [PSCustomObject]@{Name = "Uzbekistan"; Code = "UZ"},
    [PSCustomObject]@{Name = "Vanuatu"; Code = "VU"},
    [PSCustomObject]@{Name = "Venezuela"; Code = "VE"},
    [PSCustomObject]@{Name = "Vietnam"; Code = "VN"},
    [PSCustomObject]@{Name = "Wallis and Futuna"; Code = "WF"},
    [PSCustomObject]@{Name = "Yemen"; Code = "YE"},
    [PSCustomObject]@{Name = "Zambia"; Code = "ZM"},
    [PSCustomObject]@{Name = "Zimbabwe"; Code = "ZW"}
    )

    try {
        Import-Module Microsoft.Graph.Identity.SignIns -ErrorAction Stop
        
        $params = @{
            "@odata.type" = "#microsoft.graph.countryNamedLocation"
            displayName = $DisplayName
            countriesAndRegions = $CountryCodes
            includeUnknownCountriesAndRegions = $IncludeUnknownCountriesAndRegions
        }
        
        $namedLocation = New-MgIdentityConditionalAccessNamedLocation -BodyParameter $params
        
        return $namedLocation
    }
    catch {
        Write-Error "Failed to create named location: $_"
        throw
    }

}

